name: Build

on: [push]

jobs:

  test:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-latest ]

    name: Test job ${{ matrix.java }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        java-package: jdk
        architecture: x64

    - name: Test Deploy
      run: ./gradlew update -PrunList=main -PmainUrl='jdbc:postgresql://localhost:5432/postgres' -PmainUsername=postgres -PmainPassword=postgres
